#!/usr/bin/env bash
# Launcher for running multiple face-recognition-service instances on a single
# multi-GPU vast.ai host. Pins each instance to a specific GPU via
# CUDA_VISIBLE_DEVICES, enables TensorRT FP16, exposes a local Caddy
# round-robin LB, and (optionally) a Cloudflare Named Tunnel.
#
# Usage:
#   ./run_instances.sh start | stop | restart | status | urls
#
# Edit the INSTANCES array below for your topology. Defaults: 3 per GPU on
# a 3-GPU host (9 instances total).
#
# Environment overrides:
#   FACE_MODEL_DIR        Where InsightFace caches model files (default: /root/.insightface)
#   LB_PORT               Internal port for the Caddy LB (default: 7999)
#   CLOUDFLARED_BIN       Path to cloudflared (default: search PATH then vast portal path)
#   CLOUDFLARED_ENABLE    Set to 0 to skip Cloudflare tunnel (default: 1 if cert.pem exists)
#   CLOUDFLARED_DOMAIN    Root domain for tunnel hostnames (default: infected.life)
#   CLOUDFLARED_TUNNEL    Named tunnel name (default: face-recognition-pool)

set -euo pipefail

# ── Discover repo root (works regardless of where script is invoked from)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR"
while [[ "$ROOT" != "/" && ! -f "$ROOT/pyproject.toml" ]]; do
  ROOT="$(dirname "$ROOT")"
done
if [[ ! -f "$ROOT/pyproject.toml" ]]; then
  echo "Could not find repo root (pyproject.toml) from $SCRIPT_DIR" >&2
  exit 1
fi
SP="$ROOT/.venv/lib/python3.12/site-packages"

# CUDA 12 runtime libs + TensorRT come from pip wheels — wire them via LD_LIBRARY_PATH.
export LD_LIBRARY_PATH="\
$SP/tensorrt_libs:\
$SP/nvidia/cublas/lib:\
$SP/nvidia/cudnn/lib:\
$SP/nvidia/curand/lib:\
$SP/nvidia/cufft/lib:\
$SP/nvidia/cusparse/lib:\
$SP/nvidia/cusolver/lib:\
$SP/nvidia/nvjitlink/lib:\
$SP/nvidia/cuda_runtime/lib:\
$SP/nvidia/cuda_nvrtc/lib:\
${LD_LIBRARY_PATH:-}"

LOG_DIR="$SCRIPT_DIR/logs"
PID_DIR="$SCRIPT_DIR/run"
TRT_DIR="$SCRIPT_DIR/trt_cache"
mkdir -p "$LOG_DIR" "$PID_DIR" "$TRT_DIR"

# ── Topology: instance_id  gpu_index  local_port (loopback)
#    Default: 3 instances per GPU on a 3-GPU host. Edit freely.
INSTANCES=(
  "gpu0-a 0 11113"
  "gpu0-b 0 11114"
  "gpu0-c 0 11115"
  "gpu1-a 1 11119"
  "gpu1-b 1 11120"
  "gpu1-c 1 11121"
  "gpu2-a 2 11125"
  "gpu2-b 2 11126"
  "gpu2-c 2 11127"
)

# ── Config knobs
FACE_MODEL_DIR="${FACE_MODEL_DIR:-/root/.insightface}"
LB_PORT="${LB_PORT:-7999}"
CLOUDFLARED_DOMAIN="${CLOUDFLARED_DOMAIN:-infected.life}"
CLOUDFLARED_TUNNEL="${CLOUDFLARED_TUNNEL:-face-recognition-pool}"

# Resolve cloudflared binary (PATH > vast portal copy > skip)
if [[ -z "${CLOUDFLARED_BIN:-}" ]]; then
  if command -v cloudflared >/dev/null 2>&1; then
    CLOUDFLARED_BIN="$(command -v cloudflared)"
  elif [[ -x /opt/portal-aio/tunnel_manager/cloudflared ]]; then
    CLOUDFLARED_BIN=/opt/portal-aio/tunnel_manager/cloudflared
  fi
fi

# Auto-enable Cloudflare tunnel only if cloudflared + cert.pem are present.
if [[ -z "${CLOUDFLARED_ENABLE:-}" ]]; then
  if [[ -n "${CLOUDFLARED_BIN:-}" && -f /root/.cloudflared/cert.pem ]]; then
    CLOUDFLARED_ENABLE=1
  else
    CLOUDFLARED_ENABLE=0
  fi
fi

CADDY_BIN="${CADDY_BIN:-}"
if [[ -z "$CADDY_BIN" ]]; then
  if command -v caddy >/dev/null 2>&1; then
    CADDY_BIN="$(command -v caddy)"
  elif [[ -x /opt/instance-tools/bin/caddy ]]; then
    CADDY_BIN=/opt/instance-tools/bin/caddy
  fi
fi

CADDY_CFG="$SCRIPT_DIR/caddy_lb.generated.conf"
CADDY_PIDFILE="$PID_DIR/lb-caddy.pid"
CADDY_LOG="$LOG_DIR/lb-caddy.log"

CLOUDFLARED_CFG="$SCRIPT_DIR/cloudflared.generated.yml"
CLOUDFLARED_PIDFILE="$PID_DIR/named-tunnel.pid"
CLOUDFLARED_LOG="$LOG_DIR/named-tunnel.log"

URLS_FILE="$PID_DIR/public_urls.txt"

# ── Helpers
gen_caddy() {
  local upstreams=""
  for line in "${INSTANCES[@]}"; do
    # shellcheck disable=SC2086
    set -- $line
    upstreams="$upstreams 127.0.0.1:$3"
  done
  cat >"$CADDY_CFG" <<EOF
# Generated by run_instances.sh — do not edit by hand.
:${LB_PORT} {
	encode zstd gzip
	reverse_proxy${upstreams} {
		lb_policy least_conn
		lb_try_duration 5s
		fail_duration 10s
		health_uri /health
		health_interval 10s
		health_timeout 2s
		header_up Host {upstream_hostport}
		header_up X-Real-IP {remote_host}
		flush_interval -1
	}
}
EOF
}

# Discover the (single) named tunnel credentials JSON next to cert.pem
find_tunnel_creds() {
  local creds
  creds=$(ls /root/.cloudflared/*.json 2>/dev/null | head -1)
  if [[ -z "$creds" ]]; then
    echo "No tunnel credentials in /root/.cloudflared/. Run:" >&2
    echo "  cloudflared tunnel create $CLOUDFLARED_TUNNEL" >&2
    return 1
  fi
  echo "$creds"
}

gen_cloudflared() {
  local creds tunnel_id
  creds=$(find_tunnel_creds) || return 1
  tunnel_id=$(basename "$creds" .json)
  {
    echo "tunnel: $tunnel_id"
    echo "credentials-file: $creds"
    echo "no-autoupdate: true"
    echo "metrics: 127.0.0.1:11200"
    echo ""
    echo "ingress:"
    echo "  - hostname: fr-pool.${CLOUDFLARED_DOMAIN}"
    echo "    service: http://127.0.0.1:${LB_PORT}"
    echo ""
    for line in "${INSTANCES[@]}"; do
      # shellcheck disable=SC2086
      set -- $line
      echo "  - hostname: $1.${CLOUDFLARED_DOMAIN}"
      echo "    service: http://127.0.0.1:$3"
    done
    echo ""
    echo "  - service: http_status:404"
  } >"$CLOUDFLARED_CFG"
}

# Pre-create CF DNS routes (CNAMEs). Idempotent — re-runs are safe.
provision_dns() {
  [[ "${CLOUDFLARED_ENABLE}" != "1" ]] && return 0
  [[ -z "${CLOUDFLARED_BIN:-}" ]] && return 0
  echo "[dns] provisioning Cloudflare CNAMEs (idempotent)..."
  "$CLOUDFLARED_BIN" tunnel route dns "$CLOUDFLARED_TUNNEL" "fr-pool.${CLOUDFLARED_DOMAIN}" 2>&1 | tail -1 || true
  for line in "${INSTANCES[@]}"; do
    # shellcheck disable=SC2086
    set -- $line
    "$CLOUDFLARED_BIN" tunnel route dns "$CLOUDFLARED_TUNNEL" "$1.${CLOUDFLARED_DOMAIN}" 2>&1 | tail -1 || true
  done
}

# ── Per-instance lifecycle
start_one() {
  local name="$1" gpu="$2" port="$3"
  local trt_cache="$TRT_DIR/$name"
  local log="$LOG_DIR/$name.log"
  local pidfile="$PID_DIR/$name.pid"

  mkdir -p "$trt_cache"

  if [[ -f "$pidfile" ]] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
    echo "[$name] already running (pid $(cat "$pidfile"))"
    return
  fi

  echo "[$name] starting on GPU $gpu, port $port (TRT cache: $trt_cache)"
  CUDA_VISIBLE_DEVICES="$gpu" \
  FACE_USE_GPU=true \
  FACE_USE_TENSORRT=true \
  FACE_CTX_ID=0 \
  FACE_MODEL_DIR="$FACE_MODEL_DIR" \
  FACE_TRT_CACHE_PATH="$trt_cache" \
  APP_NAME="face-recognition-$name" \
    nohup "$ROOT/.venv/bin/uvicorn" src.main:app \
      --app-dir "$ROOT" \
      --host 127.0.0.1 --port "$port" \
      --workers 1 \
      --log-level info \
      >>"$log" 2>&1 &
  echo $! >"$pidfile"
}

stop_one() {
  local name="$1"
  local pidfile="$PID_DIR/$name.pid"
  if [[ -f "$pidfile" ]]; then
    local pid; pid=$(cat "$pidfile")
    if kill -0 "$pid" 2>/dev/null; then
      echo "[$name] stopping pid $pid"
      kill "$pid"
      for _ in {1..30}; do kill -0 "$pid" 2>/dev/null || break; sleep 0.5; done
      kill -9 "$pid" 2>/dev/null || true
    fi
    rm -f "$pidfile"
  fi
}

status_one() {
  local name="$1" port="$3"
  local pidfile="$PID_DIR/$name.pid"
  local pid="-" state="DOWN"
  if [[ -f "$pidfile" ]] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
    pid=$(cat "$pidfile"); state="UP"
  fi
  local health
  health=$(curl -s -o /dev/null -w "%{http_code}" --max-time 2 "http://127.0.0.1:$port/health" || true)
  printf "  %-7s pid=%-7s port=%-5s state=%-5s health=%s\n" "$name" "$pid" "$port" "$state" "$health"
}

# ── LB
start_lb() {
  if [[ -z "${CADDY_BIN:-}" ]]; then
    echo "[lb-caddy] caddy binary not found — skipping LB"
    return
  fi
  if [[ -f "$CADDY_PIDFILE" ]] && kill -0 "$(cat "$CADDY_PIDFILE")" 2>/dev/null; then
    echo "[lb-caddy] already running (pid $(cat "$CADDY_PIDFILE"))"
    return
  fi
  gen_caddy
  echo "[lb-caddy] starting internal LB on :$LB_PORT (config: $CADDY_CFG)"
  : >"$CADDY_LOG"
  nohup "$CADDY_BIN" run --config "$CADDY_CFG" --adapter caddyfile \
    >>"$CADDY_LOG" 2>&1 &
  echo $! >"$CADDY_PIDFILE"
}

stop_lb() {
  if [[ -f "$CADDY_PIDFILE" ]]; then
    local pid; pid=$(cat "$CADDY_PIDFILE")
    if kill -0 "$pid" 2>/dev/null; then
      echo "[lb-caddy] stopping pid $pid"
      kill "$pid"
      for _ in {1..10}; do kill -0 "$pid" 2>/dev/null || break; sleep 0.5; done
      kill -9 "$pid" 2>/dev/null || true
    fi
    rm -f "$CADDY_PIDFILE"
  fi
}

# ── Cloudflare Named Tunnel
start_tunnel() {
  : >"$URLS_FILE"
  printf "%-7s -> http://127.0.0.1:%s  (Caddy LB, round-robin)\n" "LB" "$LB_PORT" | tee -a "$URLS_FILE"
  for line in "${INSTANCES[@]}"; do
    # shellcheck disable=SC2086
    set -- $line
    printf "%-7s -> http://127.0.0.1:%s\n" "$1" "$3" | tee -a "$URLS_FILE"
  done

  if [[ "$CLOUDFLARED_ENABLE" != "1" ]]; then
    return 0
  fi

  if ! gen_cloudflared; then
    echo "[named-tunnel] config generation failed — skipping tunnel"
    return 0
  fi

  if [[ -f "$CLOUDFLARED_PIDFILE" ]] && kill -0 "$(cat "$CLOUDFLARED_PIDFILE")" 2>/dev/null; then
    echo "[named-tunnel] already running (pid $(cat "$CLOUDFLARED_PIDFILE"))"
  else
    echo "[named-tunnel] starting cloudflared (Named Tunnel: $CLOUDFLARED_TUNNEL)"
    : >"$CLOUDFLARED_LOG"
    nohup "$CLOUDFLARED_BIN" --config "$CLOUDFLARED_CFG" tunnel run "$CLOUDFLARED_TUNNEL" \
      >>"$CLOUDFLARED_LOG" 2>&1 &
    echo $! >"$CLOUDFLARED_PIDFILE"
  fi

  # Public hostname listing (append CF-routed URLs to URLS_FILE)
  : >"$URLS_FILE"
  printf "%-7s -> https://fr-pool.%s  (LB, round-robin)\n" "LB" "$CLOUDFLARED_DOMAIN" | tee -a "$URLS_FILE"
  for line in "${INSTANCES[@]}"; do
    # shellcheck disable=SC2086
    set -- $line
    printf "%-7s -> https://%s.%s\n" "$1" "$1" "$CLOUDFLARED_DOMAIN" | tee -a "$URLS_FILE"
  done
}

stop_tunnel() {
  if [[ -f "$CLOUDFLARED_PIDFILE" ]]; then
    local pid; pid=$(cat "$CLOUDFLARED_PIDFILE")
    if kill -0 "$pid" 2>/dev/null; then
      echo "[named-tunnel] stopping pid $pid"
      kill "$pid"
      for _ in {1..10}; do kill -0 "$pid" 2>/dev/null || break; sleep 0.5; done
      kill -9 "$pid" 2>/dev/null || true
    fi
    rm -f "$CLOUDFLARED_PIDFILE"
  fi
}

# ── Dispatch
cmd="${1:-start}"
case "$cmd" in
  start)
    for line in "${INSTANCES[@]}"; do
      # shellcheck disable=SC2086
      start_one $line
    done
    start_lb
    start_tunnel
    ;;
  stop)
    stop_tunnel
    stop_lb
    for line in "${INSTANCES[@]}"; do
      # shellcheck disable=SC2086
      stop_one $line
    done
    ;;
  restart)
    "$0" stop
    "$0" start
    ;;
  status)
    echo "Instances:"
    for line in "${INSTANCES[@]}"; do
      # shellcheck disable=SC2086
      status_one $line
    done
    local_pid="-"; local_state="DOWN"
    if [[ -f "$CADDY_PIDFILE" ]] && kill -0 "$(cat "$CADDY_PIDFILE")" 2>/dev/null; then
      local_pid=$(cat "$CADDY_PIDFILE"); local_state="UP"
    fi
    health=$(curl -s -o /dev/null -w "%{http_code}" --max-time 2 "http://127.0.0.1:$LB_PORT/health" || true)
    printf "  %-7s pid=%-7s port=%-5s state=%-5s health=%s\n" "lb-caddy" "$local_pid" "$LB_PORT" "$local_state" "$health"
    if [[ "$CLOUDFLARED_ENABLE" == "1" ]]; then
      cf_pid="-"; cf_state="DOWN"
      if [[ -f "$CLOUDFLARED_PIDFILE" ]] && kill -0 "$(cat "$CLOUDFLARED_PIDFILE")" 2>/dev/null; then
        cf_pid=$(cat "$CLOUDFLARED_PIDFILE"); cf_state="UP"
      fi
      printf "  %-7s pid=%-7s port=%-5s state=%s\n" "tunnel" "$cf_pid" "QUIC" "$cf_state"
    fi
    echo ""
    echo "URLs:"
    if [[ -s "$URLS_FILE" ]]; then sed 's/^/  /' "$URLS_FILE"; else echo "  (none — run start first)"; fi
    ;;
  urls)
    [[ -s "$URLS_FILE" ]] && cat "$URLS_FILE" || { echo "no URLs yet — run start" >&2; exit 1; }
    ;;
  provision-dns)
    provision_dns
    ;;
  gen-caddy)
    gen_caddy && cat "$CADDY_CFG"
    ;;
  gen-cloudflared)
    gen_cloudflared && cat "$CLOUDFLARED_CFG"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status|urls|provision-dns|gen-caddy|gen-cloudflared}" >&2
    exit 2
    ;;
esac
